version: "3"

services:
  web:
    build:
      context: ./
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:12.5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres: